#!/usr/bin/python3
if __name__ =="__main__":
	import sys

	n = len(sys.argv)
	print("{}" .format(n))
	for i in range(1, n+1):
		argv_sum = int (sys.argv[i] + sys.argv[i + 1])
	print("{}" .format(argv_sum))
